// Chinawheely — Smart Distance Estimation Database
// Version: 1.0 | Coverage target: 95%+ of common hotels, districts, landmarks
// Format: keyword -> {dist: km from city center, zone: 'area name'}
// Matching: case-insensitive substring search
// Distance calculation: airport_dist + zone_dist → distance range

const cityZones = {

  // ============================================================
  //  SHANGHAI — 上海
  //  Airports: PVG (Pudong) 45km, SHA (Hongqiao) 15km
  //  Keywords: ~350 entries
  // ============================================================
  shanghai: {
    airports: { PVG: 45, SHA: 15 },
    zones: {
      // ─── International Luxury Hotels ───
      'park hyatt': { dist: 2, zone: 'Lujiazui' },
      'the peninsula': { dist: 2, zone: 'The Bund' },
      'fairmont peace': { dist: 2, zone: 'Nanjing Road' },
      'waldorf astoria': { dist: 2, zone: 'The Bund' },
      'jumeirah himalayas': { dist: 3, zone: 'Pudong' },
      'ritz carlton': { dist: 2, zone: 'Pudong' },
      'four seasons pudong': { dist: 2, zone: 'Pudong' },
      'four seasons jingan': { dist: 3, zone: "Jing'an" },
      'mandarin oriental pudong': { dist: 2, zone: 'Pudong' },
      'hyatt on the bund': { dist: 3, zone: 'The Bund' },
      'intercontinental shanghai': { dist: 3, zone: 'Nanjing Road' },
      'grand hyatt shanghai': { dist: 3, zone: "Jing'an" },
      'pudong shangri-la': { dist: 2, zone: 'Lujiazui' },
      'jing an shangri-la': { dist: 3, zone: "Jing'an" },
      'pullman shanghai': { dist: 4, zone: "Jing'an" },
      'marriott city centre': { dist: 3, zone: "People's Square" },
      'marriott pudong': { dist: 4, zone: 'Pudong' },
      'hilton shanghai': { dist: 4, zone: 'Hongkou' },
      'sheraton shanghai': { dist: 5, zone: 'Hongkou' },
      'westin bund center': { dist: 3, zone: 'The Bund' },
      'conrad shanghai': { dist: 4, zone: 'Lujiazui' },
      'edition shanghai': { dist: 3, zone: 'Nanjing Road' },
      'w hotel shanghai': { dist: 3, zone: 'The Bund' },
      'andaz shanghai': { dist: 3, zone: 'Xintiandi' },
      'banyan tree shanghai': { dist: 5, zone: 'Minhang' },
      'st regis shanghai': { dist: 3, zone: "Jing'an" },
      'rosewood shanghai': { dist: 3, zone: "Jing'an" },
      'amanyangyun': { dist: 35, zone: 'Minhang' },
      'the middle house': { dist: 3, zone: "Jing'an" },
      'swire': { dist: 3, zone: "Jing'an" },
      'bvlgari shanghai': { dist: 4, zone: "Jing'an" },
      'one sino park': { dist: 4, zone: 'Xuhui' },
      'j hotel shanghai': { dist: 2, zone: 'Lujiazui' },
      'regent shanghai': { dist: 3, zone: 'Lujiazui' },
      'langham xintiandi': { dist: 3, zone: 'Xintiandi' },
      'okura garden': { dist: 4, zone: 'Xuhui' },
      'okura shanghai': { dist: 4, zone: 'Xuhui' },
      'nikko shanghai': { dist: 4, zone: 'Pudong' },
      'millennium hongqiao': { dist: 3, zone: 'Lujiazui' },
      'sukhothai shanghai': { dist: 3, zone: "Jing'an" },
      'anandi shanghai': { dist: 6, zone: 'Putuo' },
      'blossom house': { dist: 5, zone: 'Xuhui' },
      'kimpton shanghai': { dist: 3, zone: "Jing'an" },
      'jw marriott tomorrow': { dist: 3, zone: 'Pudong' },
      'jw marriott shanghai': { dist: 3, zone: 'Pudong' },

      // ─── Mid-Range / Business Hotels ───
      'courtyard shanghai': { dist: 4, zone: 'Pudong' },
      'renaissance shanghai': { dist: 4, zone: 'Pudong' },
      'doubletree shanghai': { dist: 5, zone: 'Pudong' },
      'ac hotel shanghai': { dist: 4, zone: 'Hongqiao' },
      'moxy shanghai': { dist: 4, zone: 'Hongqiao' },
      'autograph shanghai': { dist: 4, zone: 'Xuhui' },
      'aloft shanghai': { dist: 5, zone: 'Pudong' },
      'element shanghai': { dist: 5, zone: 'Pudong' },
      'indigo shanghai': { dist: 3, zone: "Jing'an" },
      'mercure shanghai': { dist: 4, zone: 'Pudong' },
      'novotel shanghai': { dist: 4, zone: 'Pudong' },
      'ibis shanghai': { dist: 4, zone: 'Hongqiao' },
      'holiday inn shanghai': { dist: 4, zone: 'Pudong' },
      'crown plaza shanghai': { dist: 4, zone: 'Pudong' },
      'voco shanghai': { dist: 4, zone: 'Pudong' },
      'urcove hyatt': { dist: 4, zone: 'Hongqiao' },
      'urcove shanghai': { dist: 4, zone: 'Hongqiao' },
      'residence inn shanghai': { dist: 4, zone: 'Pudong' },
      'townplace shanghai': { dist: 4, zone: "Jing'an" },
      'ascott shanghai': { dist: 4, zone: 'Pudong' },
      'somerset shanghai': { dist: 4, zone: 'Pudong' },
      'fraser shanghai': { dist: 4, zone: "Jing'an" },
      'oakwood shanghai': { dist: 4, zone: "Jing'an" },
      'citadines shanghai': { dist: 4, zone: 'Pudong' },
      'lyf shanghai': { dist: 4, zone: 'Hongqiao' },
      'base shanghai': { dist: 4, zone: 'Hongqiao' },
      'modena shanghai': { dist: 4, zone: "Jing'an" },
      'vienna hotel': { dist: 4, zone: 'Pudong' },
      'all seasons shanghai': { dist: 4, zone: 'Pudong' },
      'home inn shanghai': { dist: 4, zone: 'Pudong' },
      'hanting hotel': { dist: 4, zone: 'Pudong' },
      'ji hotel shanghai': { dist: 4, zone: 'Pudong' },
      'orange hotel': { dist: 4, zone: 'Pudong' },
      'starway hotel': { dist: 4, zone: 'Pudong' },
      'elan hotel': { dist: 4, zone: 'Pudong' },
      'haiyou hotel': { dist: 4, zone: 'Pudong' },
      'yitel shanghai': { dist: 4, zone: 'Pudong' },
      'citigo shanghai': { dist: 4, zone: 'Pudong' },
      'manxin shanghai': { dist: 4, zone: 'Pudong' },
      'xana hotel': { dist: 4, zone: 'Pudong' },
      'lavande hotel': { dist: 4, zone: 'Pudong' },
      'campanile shanghai': { dist: 4, zone: 'Pudong' },
      'citic pacific': { dist: 4, zone: "Jing'an" },
      'yihe hotel': { dist: 4, zone: 'Pudong' },
      'regal plaza': { dist: 4, zone: 'Pudong' },
      'sunworld hotel': { dist: 3, zone: 'Nanjing Road' },
      'broadway mansions': { dist: 3, zone: 'Hongkou' },
      'astor house': { dist: 3, zone: 'Hongkou' },
      'peace hotel': { dist: 2, zone: 'The Bund' },
      'cathay hotel': { dist: 3, zone: 'Nanjing Road' },
      'park hotel shanghai': { dist: 3, zone: "People's Square" },
      'jinjiang hotel': { dist: 3, zone: 'Luwan' },
      'new world shanghai': { dist: 3, zone: 'Nanjing Road' },
      'mayfair hotel': { dist: 3, zone: "Jing'an" },
      'west bund hotel': { dist: 5, zone: 'Xuhui' },

      // ─── Historic / Boutique Hotels ───
      'jade buddha hotel': { dist: 4, zone: "Jing'an" },
      'junting hotel': { dist: 4, zone: 'Pudong' },
      'dazhong hotel': { dist: 4, zone: 'Pudong' },
      'jingjiang hotel': { dist: 3, zone: 'Luwan' },
      'puli hotel': { dist: 3, zone: "Jing'an" },
      'urbn hotel': { dist: 3, zone: "Jing'an" },
      'waterhouse': { dist: 3, zone: 'Nanjing Road' },
      'kapok shanghai': { dist: 3, zone: "Jing'an" },
      'ssaw hotel': { dist: 4, zone: 'Pudong' },
      'ssaw boutique': { dist: 4, zone: 'Pudong' },
      'ssaw plaza': { dist: 4, zone: 'Pudong' },
      'ssaw': { dist: 4, zone: 'Pudong' },
      'yaang life': { dist: 3, zone: "Jing'an" },
      'the drama': { dist: 3, zone: "Jing'an" },
      'shanghai mansion': { dist: 2, zone: 'The Bund' },
      'atour hotel': { dist: 4, zone: 'Pudong' },
      'atour shanghai': { dist: 4, zone: 'Pudong' },
      'citi hotel': { dist: 4, zone: 'Pudong' },
      'citi shanghai': { dist: 4, zone: 'Pudong' },
      'orange crystal': { dist: 4, zone: 'Pudong' },
      'chinese hotel': { dist: 4, zone: 'Pudong' },
      'super 8': { dist: 5, zone: 'Pudong' },
      'motel 168': { dist: 5, zone: 'Pudong' },
      'jinjiang inn': { dist: 4, zone: 'Pudong' },
      '7 days': { dist: 5, zone: 'Pudong' },
      'greentree': { dist: 5, zone: 'Pudong' },
      'shell hotel': { dist: 5, zone: 'Pudong' },
      'oyo': { dist: 5, zone: 'Pudong' },
      'bai na': { dist: 5, zone: 'Pudong' },
      'zsmart': { dist: 5, zone: 'Pudong' },
      'joya hotel': { dist: 4, zone: 'Pudong' },
      'renaissance zhongshan': { dist: 4, zone: 'Changning' },

      // ─── Core Districts / Landmarks ───
      'the bund': { dist: 2, zone: 'The Bund' },
      'waitan': { dist: 2, zone: 'The Bund' },
      'lujiazui': { dist: 2, zone: 'Lujiazui' },
      'nanjing road': { dist: 2, zone: 'Nanjing Road' },
      'nanjing dong lu': { dist: 2, zone: 'Nanjing Road' },
      'nanjing xi lu': { dist: 3, zone: "Jing'an" },
      'xintiandi': { dist: 3, zone: 'Xintiandi' },
      'french concession': { dist: 4, zone: 'Former French Concession' },
      "jing'an": { dist: 3, zone: "Jing'an" },
      'jing an': { dist: 3, zone: "Jing'an" },
      "people's square": { dist: 2, zone: "People's Square" },
      'renmin square': { dist: 2, zone: "People's Square" },
      'huangpu': { dist: 2, zone: 'Huangpu' },
      'pudong': { dist: 8, zone: 'Pudong' },
      'hongqiao': { dist: 3, zone: 'Hongqiao' },
      'changning': { dist: 5, zone: 'Changning' },
      'xuhui': { dist: 4, zone: 'Xuhui' },
      'yangpu': { dist: 6, zone: 'Yangpu' },
      'hongkou': { dist: 4, zone: 'Hongkou' },
      'putuo': { dist: 5, zone: 'Putuo' },
      'zhabei': { dist: 4, zone: 'Zhabei' },
      'luwan': { dist: 3, zone: 'Luwan' },
      'minhang': { dist: 10, zone: 'Minhang' },
      'jiading': { dist: 15, zone: 'Jiading' },
      'songjiang': { dist: 25, zone: 'Songjiang' },
      'qingpu': { dist: 20, zone: 'Qingpu' },
      'baoshan': { dist: 12, zone: 'Baoshan' },
      'fengxian': { dist: 30, zone: 'Fengxian' },
      'jinshan': { dist: 35, zone: 'Jinshan' },
      'chongming': { dist: 45, zone: 'Chongming' },
      'dishui lake': { dist: 50, zone: 'Pudong' },
      'lingang': { dist: 50, zone: 'Pudong' },

      // ─── Landmarks & Tourist Spots ───
      'oriental pearl': { dist: 2, zone: 'Lujiazui' },
      'shanghai tower': { dist: 2, zone: 'Lujiazui' },
      'jinmao tower': { dist: 2, zone: 'Lujiazui' },
      'world financial center': { dist: 2, zone: 'Lujiazui' },
      'shanghai world financial': { dist: 2, zone: 'Lujiazui' },
      'swfc': { dist: 2, zone: 'Lujiazui' },
      'yuyuan garden': { dist: 2, zone: 'Old City' },
      'yu garden': { dist: 2, zone: 'Old City' },
      'city god temple': { dist: 2, zone: 'Old City' },
      'chenghuang miao': { dist: 2, zone: 'Old City' },
      'jade buddha temple': { dist: 4, zone: "Jing'an" },
      'longhua temple': { dist: 5, zone: 'Xuhui' },
      "jing'an temple": { dist: 3, zone: "Jing'an" },
      'jing an temple': { dist: 3, zone: "Jing'an" },
      'disneyland': { dist: 25, zone: 'Pudong' },
      'disney': { dist: 25, zone: 'Pudong' },
      'shanghai disney': { dist: 25, zone: 'Pudong' },
      'wild animal park': { dist: 25, zone: 'Pudong' },
      'zoo': { dist: 5, zone: 'Changning' },
      'botanical garden': { dist: 8, zone: 'Xuhui' },
      'century park': { dist: 8, zone: 'Pudong' },
      'gucun park': { dist: 15, zone: 'Baoshan' },
      'gongqing forest': { dist: 7, zone: 'Yangpu' },
      'sheshan': { dist: 25, zone: 'Songjiang' },
      'zhujiajiao': { dist: 30, zone: 'Qingpu' },
      'qibao': { dist: 12, zone: 'Minhang' },
      'xinchang': { dist: 25, zone: 'Pudong' },
      'zhujiajiao ancient': { dist: 30, zone: 'Qingpu' },
      'water town': { dist: 30, zone: 'Qingpu' },
      'tianzifang': { dist: 3, zone: 'Luwan' },
      'tian zi fang': { dist: 3, zone: 'Luwan' },
      'm50': { dist: 4, zone: 'Putuo' },
      '1933': { dist: 4, zone: 'Hongkou' },
      'power station': { dist: 5, zone: 'Xuhui' },
      'long museum': { dist: 5, zone: 'Xuhui' },
      'rockbund': { dist: 2, zone: 'The Bund' },
      'rock bund': { dist: 2, zone: 'The Bund' },

      // ─── Transport Hubs ───
      'pudong airport': { dist: 0, zone: 'PVG' },
      'pudong international': { dist: 0, zone: 'PVG' },
      'hongqiao airport': { dist: 0, zone: 'SHA' },
      'hongqiao international': { dist: 0, zone: 'SHA' },
      'hongqiao railway': { dist: 3, zone: 'Hongqiao' },
      'hongqiao station': { dist: 3, zone: 'Hongqiao' },
      'shanghai railway': { dist: 2, zone: "Jing'an" },
      'shanghai station': { dist: 2, zone: "Jing'an" },
      'south railway': { dist: 8, zone: 'Xuhui' },
      'shanghai south': { dist: 8, zone: 'Xuhui' },
      'west railway': { dist: 6, zone: 'Changning' },
      'north railway': { dist: 4, zone: "Jing'an" },
      'cruise terminal': { dist: 4, zone: 'Hongkou' },
      'wusongkou': { dist: 5, zone: 'Baoshan' },

      // ─── Major Roads / Areas ───
      'huaihai road': { dist: 3, zone: 'Luwan' },
      'huaihai lu': { dist: 3, zone: 'Luwan' },
      'xujiahui': { dist: 4, zone: 'Xuhui' },
      'hengshan road': { dist: 4, zone: 'Xuhui' },
      'fuxing road': { dist: 4, zone: 'Xuhui' },
      'wukang road': { dist: 4, zone: 'Xuhui' },
      'anfu road': { dist: 4, zone: 'Xuhui' },
      'wuding road': { dist: 3, zone: "Jing'an" },
      'julu road': { dist: 3, zone: "Jing'an" },
      'fumin road': { dist: 3, zone: "Jing'an" },
      'changle road': { dist: 3, zone: "Jing'an" },
      "yan'an road": { dist: 3, zone: "Jing'an" },
      'yan an road': { dist: 3, zone: "Jing'an" },
      'suzhou creek': { dist: 3, zone: 'Hongkou' },
      'suzhou river': { dist: 3, zone: 'Hongkou' },
      'huangpu river': { dist: 2, zone: 'The Bund' },
      'west bund': { dist: 5, zone: 'Xuhui' },
      'zhangjiang': { dist: 12, zone: 'Pudong' },
      'jinqiao': { dist: 10, zone: 'Pudong' },
      'waigaoqiao': { dist: 12, zone: 'Pudong' },
      'tangzhen': { dist: 15, zone: 'Pudong' },
      'sanlin': { dist: 8, zone: 'Pudong' },
      'chuansha': { dist: 18, zone: 'Pudong' },
      'nanxiang': { dist: 12, zone: 'Jiading' },
      'jiangqiao': { dist: 10, zone: 'Jiading' },
      'sijing': { dist: 20, zone: 'Songjiang' },
      'jiuting': { dist: 18, zone: 'Songjiang' },

      // ─── Universities ───
      'fudan university': { dist: 6, zone: 'Yangpu' },
      'fudan': { dist: 6, zone: 'Yangpu' },
      'tongji university': { dist: 6, zone: 'Yangpu' },
      'tongji': { dist: 6, zone: 'Yangpu' },
      'sjtu': { dist: 8, zone: 'Xuhui' },
      'jiao tong': { dist: 8, zone: 'Xuhui' },
      'shanghai jiao tong': { dist: 8, zone: 'Xuhui' },
      'ecnu': { dist: 5, zone: 'Putuo' },
      'east china normal': { dist: 5, zone: 'Putuo' },
      'shanghai university': { dist: 8, zone: 'Baoshan' },
      'donghua university': { dist: 5, zone: 'Changning' },
      'ecust': { dist: 6, zone: 'Xuhui' },
      'east china uni of science': { dist: 6, zone: 'Xuhui' },
      'shanghaitech': { dist: 15, zone: 'Pudong' },
      'nyu shanghai': { dist: 15, zone: 'Pudong' },
      'china europe': { dist: 12, zone: 'Pudong' },
      'ceibs': { dist: 12, zone: 'Pudong' },

      // ─── Hospitals ───
      'huashan hospital': { dist: 4, zone: "Jing'an" },
      'zhongshan hospital': { dist: 5, zone: 'Xuhui' },
      'ruijin hospital': { dist: 3, zone: 'Luwan' },
      'xinhua hospital': { dist: 6, zone: 'Yangpu' },
      'changhai hospital': { dist: 6, zone: 'Yangpu' },
      'tongji hospital': { dist: 6, zone: 'Yangpu' },
      'children hospital': { dist: 6, zone: 'Xuhui' },
      'cancer center': { dist: 5, zone: 'Xuhui' },
      'mental health center': { dist: 6, zone: 'Xuhui' },
      'renji hospital': { dist: 3, zone: 'Pudong' },
      'dongfang hospital': { dist: 6, zone: 'Pudong' },

      // ─── Default fallback ───
      'default': { dist: 25, zone: 'City Center' }
    }
  }
};

// Export for module use (if needed)
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { cityZones,

  // ============================================================
  //  BEIJING — 北京
  //  Airports: PEK (Capital) 30km, PKX (Daxing) 50km
  // ============================================================
  beijing: {
    airports: { PEK: 30, PKX: 50 },
    zones: {
      'peninsula beijing': { dist: 3, zone: 'Wangfujing' },
      'rosewood beijing': { dist: 3, zone: 'Chaoyang' },
      'waldorf astoria beijing': { dist: 2, zone: 'Wangfujing' },
      'park hyatt beijing': { dist: 3, zone: 'CBD' },
      'opposite house': { dist: 4, zone: 'Sanlitun' },
      'aman summer palace': { dist: 15, zone: 'Summer Palace' },
      'four seasons beijing': { dist: 3, zone: 'Chaoyang' },
      'st regis beijing': { dist: 3, zone: 'CBD' },
      'ritz carlton beijing': { dist: 3, zone: 'CBD' },
      'mandarin oriental beijing': { dist: 3, zone: 'Wangfujing' },
      'intercontinental beijing': { dist: 3, zone: 'Sanlitun' },
      'shangri-la beijing': { dist: 4, zone: 'CBD' },
      'grand hyatt beijing': { dist: 3, zone: 'Dongcheng' },
      'hilton beijing': { dist: 4, zone: 'Chaoyang' },
      'marriott beijing': { dist: 4, zone: 'Chaoyang' },
      'sheraton beijing': { dist: 5, zone: 'Chaoyang' },
      'westin beijing': { dist: 3, zone: 'Financial Street' },
      'conrad beijing': { dist: 4, zone: 'Chaoyang' },
      'w hotel beijing': { dist: 4, zone: 'Chaoyang' },
      'edition beijing': { dist: 4, zone: 'Sanlitun' },
      'andaz beijing': { dist: 4, zone: 'Sanlitun' },
      'banyan tree beijing': { dist: 15, zone: 'Summer Palace' },
      'kempinski beijing': { dist: 4, zone: 'Chaoyang' },
      'crowne plaza beijing': { dist: 4, zone: 'Chaoyang' },
      'new otani beijing': { dist: 4, zone: 'Chaoyang' },
      'guangdong hotel': { dist: 2, zone: 'Wangfujing' },
      'jw marriott beijing': { dist: 3, zone: 'CBD' },
      'renaissance beijing': { dist: 5, zone: 'Chaoyang' },
      'wangfujing': { dist: 3, zone: 'Wangfujing' },
      'sanlitun': { dist: 6, zone: 'Sanlitun' },
      'cbd': { dist: 15, zone: 'CBD' },
      'guomao': { dist: 15, zone: 'CBD' },
      'forbidden city': { dist: 3, zone: 'Forbidden City' },
      'tiananmen': { dist: 3, zone: 'Tiananmen' },
      'chaoyang': { dist: 10, zone: 'Chaoyang' },
      'haidian': { dist: 15, zone: 'Haidian' },
      'dongcheng': { dist: 5, zone: 'Dongcheng' },
      'xicheng': { dist: 5, zone: 'Xicheng' },
      'fengtai': { dist: 12, zone: 'Fengtai' },
      'shijingshan': { dist: 25, zone: 'Shijingshan' },
      'tongzhou': { dist: 20, zone: 'Tongzhou' },
      'shunyi': { dist: 15, zone: 'Shunyi' },
      'daxing': { dist: 20, zone: 'Daxing' },
      'changping': { dist: 25, zone: 'Changping' },
      'yanqing': { dist: 50, zone: 'Yanqing' },
      'huairou': { dist: 40, zone: 'Huairou' },
      'mentougou': { dist: 30, zone: 'Mentougou' },
      'pinggu': { dist: 45, zone: 'Pinggu' },
      'miyun': { dist: 50, zone: 'Miyun' },
      'fangshan': { dist: 25, zone: 'Fangshan' },
      'great wall': { dist: 60, zone: 'Great Wall' },
      'mutianyu': { dist: 60, zone: 'Mutianyu' },
      'badaling': { dist: 60, zone: 'Badaling' },
      'summer palace': { dist: 15, zone: 'Summer Palace' },
      'temple of heaven': { dist: 5, zone: 'Temple of Heaven' },
      'beihai park': { dist: 4, zone: 'Xicheng' },
      'jingshan park': { dist: 3, zone: 'Dongcheng' },
      'houhai': { dist: 4, zone: 'Xicheng' },
      'nanluoguxiang': { dist: 4, zone: 'Dongcheng' },
      '798': { dist: 10, zone: '798 Art Zone' },
      'olympic park': { dist: 12, zone: 'Olympic Park' },
      'bird nest': { dist: 12, zone: 'Olympic Park' },
      'water cube': { dist: 12, zone: 'Olympic Park' },
      'capital airport': { dist: 0, zone: 'PEK' },
      'beijing capital': { dist: 0, zone: 'PEK' },
      'daxing airport': { dist: 0, zone: 'PKX' },
      'beijing daxing': { dist: 0, zone: 'PKX' },
      'beijing railway': { dist: 2, zone: 'Dongcheng' },
      'beijing station': { dist: 2, zone: 'Dongcheng' },
      'beijing south': { dist: 6, zone: 'Fengtai' },
      'beijing west': { dist: 8, zone: 'Fengtai' },
      'beijing north': { dist: 5, zone: 'Xicheng' },
      'default': { dist: 20, zone: 'City Center' }
    }
  },

};