// Chinawheely - Smart Distance Estimation Database v1.0
// Coverage: 19 cities, ~1200 keywords

const cityZones = {

  // ============================================================
  //  SHANGHAI
  // ============================================================
  shanghai: {
    airports: { PVG: 45, SHA: 15 },
    zones: {
      'park hyatt': { dist: 2, zone: "Jing'an" },
      'the peninsula': { dist: 2, zone: "The Bund" },
      'fairmont peace': { dist: 2, zone: "Nanjing Road" },
      'waldorf astoria': { dist: 2, zone: "The Bund" },
      'jumeirah himalayas': { dist: 3, zone: "Pudong" },
      'ritz carlton': { dist: 2, zone: "Pudong" },
      'four seasons': { dist: 3, zone: "Jing'an" },
      'mandarin oriental': { dist: 3, zone: "Pudong" },
      'hyatt on the bund': { dist: 3, zone: "The Bund" },
      'intercontinental': { dist: 3, zone: "Nanjing Road" },
      'grand hyatt': { dist: 3, zone: "Jing'an" },
      'pudong shangri-la': { dist: 2, zone: "Lujiazui" },
      'jing an shangri-la': { dist: 3, zone: "Jing'an" },
      'marriott city centre': { dist: 3, zone: "People's Square" },
      'hilton': { dist: 4, zone: "Hongqiao" },
      'sheraton': { dist: 5, zone: "Hongkou" },
      'westin bund center': { dist: 3, zone: "The Bund" },
      'conrad': { dist: 4, zone: "Lujiazui" },
      'edition': { dist: 3, zone: "Nanjing Road" },
      'w hotel': { dist: 3, zone: "The Bund" },
      'andaz': { dist: 3, zone: "Xintiandi" },
      'banyan tree': { dist: 5, zone: "Minhang" },
      'st regis': { dist: 3, zone: "Jing'an" },
      'rosewood': { dist: 3, zone: "Jing'an" },
      'amanyangyun': { dist: 35, zone: "Minhang" },
      'the middle house': { dist: 3, zone: "Jing'an" },
      'j hotel': { dist: 2, zone: "Lujiazui" },
      'langham xintiandi': { dist: 3, zone: "Xintiandi" },
      'okura garden': { dist: 4, zone: "Xuhui" },
      'sukhothai': { dist: 3, zone: "Jing'an" },
      'anandi': { dist: 6, zone: "Putuo" },
      'blossom house': { dist: 5, zone: "Xuhui" },
      'kimpton': { dist: 3, zone: "Jing'an" },
      'jw marriott': { dist: 3, zone: "Pudong" },
      'courtyard': { dist: 4, zone: "Pudong" },
      'renaissance': { dist: 4, zone: "Pudong" },
      'doubletree': { dist: 5, zone: "Pudong" },
      'ac hotel': { dist: 4, zone: "Hongqiao" },
      'moxy': { dist: 4, zone: "Hongqiao" },
      'autograph': { dist: 4, zone: "Xuhui" },
      'aloft': { dist: 5, zone: "Pudong" },
      'element': { dist: 5, zone: "Pudong" },
      'indigo': { dist: 3, zone: "Jing'an" },
      'mercure': { dist: 4, zone: "Pudong" },
      'novotel': { dist: 4, zone: "Pudong" },
      'ibis': { dist: 4, zone: "Hongqiao" },
      'holiday inn': { dist: 4, zone: "Pudong" },
      'crown plaza': { dist: 4, zone: "Pudong" },
      'voco': { dist: 4, zone: "Pudong" },
      'urcove hyatt': { dist: 4, zone: "Hongqiao" },
      'residence inn': { dist: 4, zone: "Pudong" },
      'townplace': { dist: 4, zone: "Jing'an" },
      'ascott': { dist: 4, zone: "Pudong" },
      'somerset': { dist: 4, zone: "Pudong" },
      'fraser': { dist: 4, zone: "Jing'an" },
      'oakwood': { dist: 4, zone: "Jing'an" },
      'citadines': { dist: 4, zone: "Pudong" },
      'lyf': { dist: 4, zone: "Hongqiao" },
      'base': { dist: 4, zone: "Hongqiao" },
      'modena': { dist: 4, zone: "Jing'an" },
      'vienna hotel': { dist: 4, zone: "Pudong" },
      'all seasons': { dist: 4, zone: "Pudong" },
      'home inn': { dist: 4, zone: "Pudong" },
      'hanting hotel': { dist: 4, zone: "Pudong" },
      'ji hotel': { dist: 4, zone: "Pudong" },
      'orange hotel': { dist: 4, zone: "Pudong" },
      'starway hotel': { dist: 4, zone: "Pudong" },
      'elan hotel': { dist: 4, zone: "Pudong" },
      'haiyou hotel': { dist: 4, zone: "Pudong" },
      'yitel': { dist: 4, zone: "Pudong" },
      'citigo': { dist: 4, zone: "Pudong" },
      'manxin': { dist: 4, zone: "Pudong" },
      'xana hotel': { dist: 4, zone: "Pudong" },
      'lavande hotel': { dist: 4, zone: "Pudong" },
      'campanile': { dist: 4, zone: "Pudong" },
      'citic pacific': { dist: 4, zone: "Jing'an" },
      'yihe hotel': { dist: 4, zone: "Pudong" },
      'regal plaza': { dist: 4, zone: "Pudong" },
      'sunworld hotel': { dist: 3, zone: "Nanjing Road" },
      'broadway mansions': { dist: 3, zone: "Hongkou" },
      'astor house': { dist: 3, zone: "Hongkou" },
      'peace hotel': { dist: 2, zone: "The Bund" },
      'cathay hotel': { dist: 3, zone: "Nanjing Road" },
      'park hotel': { dist: 3, zone: "People's Square" },
      'jinjiang hotel': { dist: 3, zone: "Luwan" },
      'new world': { dist: 3, zone: "Nanjing Road" },
      'mayfair hotel': { dist: 3, zone: "Jing'an" },
      'west bund hotel': { dist: 5, zone: "Xuhui" },
      'jade buddha hotel': { dist: 4, zone: "Jing'an" },
      'junting hotel': { dist: 4, zone: "Pudong" },
      'dazhong hotel': { dist: 4, zone: "Pudong" },
      'jingjiang hotel': { dist: 3, zone: "Luwan" },
      'puli hotel': { dist: 3, zone: "Jing'an" },
      'urbn hotel': { dist: 3, zone: "Jing'an" },
      'waterhouse': { dist: 3, zone: "Nanjing Road" },
      'kapok': { dist: 3, zone: "Jing'an" },
      'ssaw hotel': { dist: 4, zone: "Pudong" },
      'ssaw boutique': { dist: 4, zone: "Pudong" },
      'ssaw plaza': { dist: 4, zone: "Pudong" },
      'yaang life': { dist: 3, zone: "Jing'an" },
      'the drama': { dist: 3, zone: "Jing'an" },
      'shanghai mansion': { dist: 2, zone: "The Bund" },
      'atour hotel': { dist: 4, zone: "Pudong" },
      'citi hotel': { dist: 4, zone: "Pudong" },
      'orange crystal': { dist: 4, zone: "Pudong" },
      'super 8': { dist: 5, zone: "Pudong" },
      'motel 168': { dist: 5, zone: "Pudong" },
      'jinjiang inn': { dist: 4, zone: "Pudong" },
      '7 days': { dist: 5, zone: "Pudong" },
      'greentree': { dist: 5, zone: "Pudong" },
      'shell hotel': { dist: 5, zone: "Pudong" },
      'oyo': { dist: 5, zone: "Pudong" },
      'bai na': { dist: 5, zone: "Pudong" },
      'zsmart': { dist: 5, zone: "Pudong" },
      'joya hotel': { dist: 4, zone: "Pudong" },
      'renaissance zhongshan': { dist: 4, zone: "Changning" },
      'the bund': { dist: 2, zone: "The Bund" },
      'waitan': { dist: 2, zone: "The Bund" },
      'lujiazui': { dist: 2, zone: "Lujiazui" },
      'nanjing road': { dist: 2, zone: "Nanjing Road" },
      'nanjing dong lu': { dist: 2, zone: "Nanjing Road" },
      'nanjing xi lu': { dist: 3, zone: "Jing'an" },
      'xintiandi': { dist: 3, zone: "Xintiandi" },
      'french concession': { dist: 4, zone: "Former French Concession" },
      "jing'an": { dist: 3, zone: "Jing'an" },
      'jing an': { dist: 3, zone: "Jing'an" },
      "people's square": { dist: 2, zone: "People's Square" },
      'renmin square': { dist: 2, zone: "People's Square" },
      'huangpu': { dist: 2, zone: "Huangpu" },
      'pudong': { dist: 8, zone: "Pudong" },
      'hongqiao': { dist: 3, zone: "Hongqiao" },
      'changning': { dist: 5, zone: "Changning" },
      'xuhui': { dist: 4, zone: "Xuhui" },
      'yangpu': { dist: 6, zone: "Yangpu" },
      'hongkou': { dist: 4, zone: "Hongkou" },
      'putuo': { dist: 5, zone: "Putuo" },
      'zhabei': { dist: 4, zone: "Zhabei" },
      'luwan': { dist: 3, zone: "Luwan" },
      'minhang': { dist: 10, zone: "Minhang" },
      'jiading': { dist: 15, zone: "Jiading" },
      'songjiang': { dist: 25, zone: "Songjiang" },
      'qingpu': { dist: 20, zone: "Qingpu" },
      'baoshan': { dist: 12, zone: "Baoshan" },
      'fengxian': { dist: 30, zone: "Fengxian" },
      'jinshan': { dist: 35, zone: "Jinshan" },
      'chongming': { dist: 45, zone: "Chongming" },
      'dishui lake': { dist: 50, zone: "Pudong" },
      'lingang': { dist: 50, zone: "Pudong" },
      'oriental pearl': { dist: 2, zone: "Lujiazui" },
      'shanghai tower': { dist: 2, zone: "Lujiazui" },
      'jinmao tower': { dist: 2, zone: "Lujiazui" },
      'world financial center': { dist: 2, zone: "Lujiazui" },
      'swfc': { dist: 2, zone: "Lujiazui" },
      'yuyuan garden': { dist: 2, zone: "Old City" },
      'yu garden': { dist: 2, zone: "Old City" },
      'city god temple': { dist: 2, zone: "Old City" },
      'chenghuang miao': { dist: 2, zone: "Old City" },
      'jade buddha temple': { dist: 4, zone: "Jing'an" },
      'longhua temple': { dist: 5, zone: "Xuhui" },
      "jing'an temple": { dist: 3, zone: "Jing'an" },
      'jing an temple': { dist: 3, zone: "Jing'an" },
      'disneyland': { dist: 25, zone: "Pudong" },
      'disney': { dist: 25, zone: "Pudong" },
      'shanghai disney': { dist: 25, zone: "Pudong" },
      'wild animal park': { dist: 25, zone: "Pudong" },
      'zoo': { dist: 5, zone: "Changning" },
      'botanical garden': { dist: 8, zone: "Xuhui" },
      'century park': { dist: 8, zone: "Pudong" },
      'gucun park': { dist: 15, zone: "Baoshan" },
      'gongqing forest': { dist: 7, zone: "Yangpu" },
      'sheshan': { dist: 25, zone: "Songjiang" },
      'zhujiajiao': { dist: 30, zone: "Qingpu" },
      'qibao': { dist: 12, zone: "Minhang" },
      'xinchang': { dist: 25, zone: "Pudong" },
      'tianzifang': { dist: 3, zone: "Luwan" },
      'tian zi fang': { dist: 3, zone: "Luwan" },
      'm50': { dist: 4, zone: "Putuo" },
      '1933': { dist: 4, zone: "Hongkou" },
      'power station': { dist: 5, zone: "Xuhui" },
      'long museum': { dist: 5, zone: "Xuhui" },
      'rockbund': { dist: 2, zone: "The Bund" },
      'rock bund': { dist: 2, zone: "The Bund" },
      'pudong airport': { dist: 0, zone: "PVG" },
      'pudong international': { dist: 0, zone: "PVG" },
      'hongqiao airport': { dist: 0, zone: "SHA" },
      'hongqiao international': { dist: 0, zone: "SHA" },
      'hongqiao railway': { dist: 3, zone: "Hongqiao" },
      'hongqiao station': { dist: 3, zone: "Hongqiao" },
      'shanghai railway': { dist: 2, zone: "Jing'an" },
      'shanghai station': { dist: 2, zone: "Jing'an" },
      'south railway': { dist: 8, zone: "Xuhui" },
      'shanghai south': { dist: 8, zone: "Xuhui" },
      'west railway': { dist: 6, zone: "Changning" },
      'north railway': { dist: 4, zone: "Jing'an" },
      'cruise terminal': { dist: 4, zone: "Hongkou" },
      'wusongkou': { dist: 5, zone: "Baoshan" },
      'huaihai road': { dist: 3, zone: "Luwan" },
      'huaihai lu': { dist: 3, zone: "Luwan" },
      'xujiahui': { dist: 4, zone: "Xuhui" },
      'hengshan road': { dist: 4, zone: "Xuhui" },
      'fuxing road': { dist: 4, zone: "Xuhui" },
      'wukang road': { dist: 4, zone: "Xuhui" },
      'anfu road': { dist: 4, zone: "Xuhui" },
      'wuding road': { dist: 3, zone: "Jing'an" },
      'julu road': { dist: 3, zone: "Jing'an" },
      'fumin road': { dist: 3, zone: "Jing'an" },
      'changle road': { dist: 3, zone: "Jing'an" },
      "yan'an road": { dist: 3, zone: "Jing'an" },
      'yan an road': { dist: 3, zone: "Jing'an" },
      'suzhou creek': { dist: 3, zone: "Hongkou" },
      'suzhou river': { dist: 3, zone: "Hongkou" },
      'huangpu river': { dist: 2, zone: "The Bund" },
      'west bund': { dist: 5, zone: "Xuhui" },
      'zhangjiang': { dist: 12, zone: "Pudong" },
      'jinqiao': { dist: 10, zone: "Pudong" },
      'waigaoqiao': { dist: 12, zone: "Pudong" },
      'tangzhen': { dist: 15, zone: "Pudong" },
      'sanlin': { dist: 8, zone: "Pudong" },
      'chuansha': { dist: 18, zone: "Pudong" },
      'nanxiang': { dist: 12, zone: "Jiading" },
      'jiangqiao': { dist: 10, zone: "Jiading" },
      'sijing': { dist: 20, zone: "Songjiang" },
      'jiuting': { dist: 18, zone: "Songjiang" },
      'fudan university': { dist: 6, zone: "Yangpu" },
      'fudan': { dist: 6, zone: "Yangpu" },
      'tongji university': { dist: 6, zone: "Yangpu" },
      'tongji': { dist: 6, zone: "Yangpu" },
      'sjtu': { dist: 8, zone: "Xuhui" },
      'jiao tong': { dist: 8, zone: "Xuhui" },
      'shanghai jiao tong': { dist: 8, zone: "Xuhui" },
      'ecnu': { dist: 5, zone: "Putuo" },
      'east china normal': { dist: 5, zone: "Putuo" },
      'shanghai university': { dist: 8, zone: "Baoshan" },
      'donghua university': { dist: 5, zone: "Changning" },
      'ecust': { dist: 6, zone: "Xuhui" },
      'east china uni of science': { dist: 6, zone: "Xuhui" },
      'shanghaitech': { dist: 15, zone: "Pudong" },
      'nyu shanghai': { dist: 15, zone: "Pudong" },
      'china europe': { dist: 12, zone: "Pudong" },
      'ceibs': { dist: 12, zone: "Pudong" },
      'huashan hospital': { dist: 4, zone: "Jing'an" },
      'zhongshan hospital': { dist: 5, zone: "Xuhui" },
      'ruijin hospital': { dist: 3, zone: "Luwan" },
      'xinhua hospital': { dist: 6, zone: "Yangpu" },
      'changhai hospital': { dist: 6, zone: "Yangpu" },
      'tongji hospital': { dist: 6, zone: "Yangpu" },
      'children hospital': { dist: 6, zone: "Xuhui" },
      'cancer center': { dist: 5, zone: "Xuhui" },
      'mental health center': { dist: 6, zone: "Xuhui" },
      'renji hospital': { dist: 3, zone: "Pudong" },
      'dongfang hospital': { dist: 6, zone: "Pudong" },
      'default': { dist: 25, zone: "City Center" }
    }
  },

  // ============================================================
  //  BEIJING
  // ============================================================
  beijing: {
    airports: { PEK: 30, PKX: 50 },
    zones: {
      'peninsula beijing': { dist: 3, zone: "Wangfujing" },
      'rosewood beijing': { dist: 3, zone: "Chaoyang" },
      'waldorf astoria beijing': { dist: 2, zone: "Wangfujing" },
      'park hyatt beijing': { dist: 3, zone: "CBD" },
      'opposite house': { dist: 4, zone: "Sanlitun" },
      'aman summer palace': { dist: 15, zone: "Summer Palace" },
      'four seasons beijing': { dist: 3, zone: "Chaoyang" },
      'st regis beijing': { dist: 3, zone: "CBD" },
      'ritz carlton beijing': { dist: 3, zone: "CBD" },
      'mandarin oriental beijing': { dist: 3, zone: "Wangfujing" },
      'intercontinental beijing': { dist: 3, zone: "Sanlitun" },
      'shangri-la beijing': { dist: 4, zone: "CBD" },
      'grand hyatt beijing': { dist: 3, zone: "Dongcheng" },
      'hilton beijing': { dist: 4, zone: "Chaoyang" },
      'marriott beijing': { dist: 4, zone: "Chaoyang" },
      'sheraton beijing': { dist: 5, zone: "Chaoyang" },
      'westin beijing': { dist: 3, zone: "Financial Street" },
      'conrad beijing': { dist: 4, zone: "Chaoyang" },
      'w hotel beijing': { dist: 4, zone: "Chaoyang" },
      'edition beijing': { dist: 4, zone: "Sanlitun" },
      'andaz beijing': { dist: 4, zone: "Sanlitun" },
      'banyan tree beijing': { dist: 15, zone: "Summer Palace" },
      'kempinski beijing': { dist: 4, zone: "Chaoyang" },
      'crowne plaza beijing': { dist: 4, zone: "Chaoyang" },
      'new otani beijing': { dist: 4, zone: "Chaoyang" },
      'guangdong hotel': { dist: 2, zone: "Wangfujing" },
      'jw marriott beijing': { dist: 3, zone: "CBD" },
      'renaissance beijing': { dist: 5, zone: "Chaoyang" },
      'wangfujing': { dist: 3, zone: "Wangfujing" },
      'sanlitun': { dist: 6, zone: "Sanlitun" },
      'cbd': { dist: 15, zone: "CBD" },
      'guomao': { dist: 15, zone: "CBD" },
      'forbidden city': { dist: 3, zone: "Forbidden City" },
      'tiananmen': { dist: 3, zone: "Tiananmen" },
      'chaoyang': { dist: 10, zone: "Chaoyang" },
      'haidian': { dist: 15, zone: "Haidian" },
      'dongcheng': { dist: 5, zone: "Dongcheng" },
      'xicheng': { dist: 5, zone: "Xicheng" },
      'fengtai': { dist: 12, zone: "Fengtai" },
      'shijingshan': { dist: 25, zone: "Shijingshan" },
      'tongzhou': { dist: 20, zone: "Tongzhou" },
      'shunyi': { dist: 15, zone: "Shunyi" },
      'daxing': { dist: 20, zone: "Daxing" },
      'changping': { dist: 25, zone: "Changping" },
      'yanqing': { dist: 50, zone: "Yanqing" },
      'huairou': { dist: 40, zone: "Huairou" },
      'mentougou': { dist: 30, zone: "Mentougou" },
      'pinggu': { dist: 45, zone: "Pinggu" },
      'miyun': { dist: 50, zone: "Miyun" },
      'fangshan': { dist: 25, zone: "Fangshan" },
      'great wall': { dist: 60, zone: "Great Wall" },
      'mutianyu': { dist: 60, zone: "Mutianyu" },
      'badaling': { dist: 60, zone: "Badaling" },
      'summer palace': { dist: 15, zone: "Summer Palace" },
      'temple of heaven': { dist: 5, zone: "Temple of Heaven" },
      'beihai park': { dist: 4, zone: "Xicheng" },
      'jingshan park': { dist: 3, zone: "Dongcheng" },
      'houhai': { dist: 4, zone: "Xicheng" },
      'nanluoguxiang': { dist: 4, zone: "Dongcheng" },
      '798': { dist: 10, zone: "798 Art Zone" },
      'olympic park': { dist: 12, zone: "Olympic Park" },
      'bird nest': { dist: 12, zone: "Olympic Park" },
      'water cube': { dist: 12, zone: "Olympic Park" },
      'capital airport': { dist: 0, zone: "PEK" },
      'beijing capital': { dist: 0, zone: "PEK" },
      'daxing airport': { dist: 0, zone: "PKX" },
      'beijing daxing': { dist: 0, zone: "PKX" },
      'beijing railway': { dist: 2, zone: "Dongcheng" },
      'beijing station': { dist: 2, zone: "Dongcheng" },
      'beijing south': { dist: 6, zone: "Fengtai" },
      'beijing west': { dist: 8, zone: "Fengtai" },
      'beijing north': { dist: 5, zone: "Xicheng" },
      'default': { dist: 20, zone: "City Center" }
    }
  },

  guangzhou: {
    airports: { CAN: 30 },
    zones: {
      'ritz carlton guangzhou': { dist: 3, zone: "Pearl River New Town" },
      'four seasons guangzhou': { dist: 3, zone: "Pearl River New Town" },
      'mandarin oriental guangzhou': { dist: 3, zone: "Tianhe" },
      'park hyatt guangzhou': { dist: 3, zone: "Tianhe" },
      'rosewood guangzhou': { dist: 3, zone: "Pearl River New Town" },
      'w guangzhou': { dist: 3, zone: "Pearl River New Town" },
      'westin guangzhou': { dist: 3, zone: "Tianhe" },
      'grand hyatt guangzhou': { dist: 3, zone: "Tianhe" },
      'shangri-la guangzhou': { dist: 5, zone: "Haizhu" },
      'hilton guangzhou': { dist: 3, zone: "Tianhe" },
      'marriott guangzhou': { dist: 3, zone: "Tianhe" },
      'sheraton guangzhou': { dist: 4, zone: "Tianhe" },
      'intercontinental guangzhou': { dist: 5, zone: "Haizhu" },
      'white swan': { dist: 4, zone: "Shamian" },
      'garden hotel': { dist: 3, zone: "Yuexiu" },
      'dongfang hotel': { dist: 3, zone: "Yuexiu" },
      'pearl river': { dist: 3, zone: "Pearl River New Town" },
      'tianhe': { dist: 5, zone: "Tianhe" },
      'yuexiu': { dist: 3, zone: "Yuexiu" },
      'liwan': { dist: 4, zone: "Liwan" },
      'haizhu': { dist: 5, zone: "Haizhu" },
      'baiyun': { dist: 10, zone: "Baiyun" },
      'huangpu gz': { dist: 15, zone: "Huangpu" },
      'panyu': { dist: 15, zone: "Panyu" },
      'nansha': { dist: 40, zone: "Nansha" },
      'luogang': { dist: 20, zone: "Luogang" },
      'zengcheng': { dist: 35, zone: "Zengcheng" },
      'conghua': { dist: 45, zone: "Conghua" },
      'huadu': { dist: 25, zone: "Huadu" },
      'shamian': { dist: 4, zone: "Shamian" },
      'beijing road': { dist: 3, zone: "Beijing Road" },
      'shangxiajiu': { dist: 4, zone: "Shangxiajiu" },
      'canton tower': { dist: 5, zone: "Haizhu" },
      'guangzhou tower': { dist: 5, zone: "Haizhu" },
      'canton fair': { dist: 8, zone: "Pazhou" },
      'pazhou': { dist: 8, zone: "Pazhou" },
      'baiyun airport': { dist: 0, zone: "CAN" },
      'guangzhou airport': { dist: 0, zone: "CAN" },
      'guangzhou south': { dist: 12, zone: "Panyu" },
      'guangzhou east': { dist: 5, zone: "Tianhe" },
      'guangzhou railway': { dist: 3, zone: "Yuexiu" },
      'default': { dist: 20, zone: "City Center" }
    }
  },
  shenzhen: {
    airports: { SZX: 35 },
    zones: {
      'park hyatt shenzhen': { dist: 3, zone: "Futian CBD" },
      'ritz carlton shenzhen': { dist: 3, zone: "Futian CBD" },
      'mandarin oriental shenzhen': { dist: 3, zone: "Futian" },
      'four seasons shenzhen': { dist: 4, zone: "Futian" },
      'st regis shenzhen': { dist: 3, zone: "Luohu" },
      'grand hyatt shenzhen': { dist: 3, zone: "Luohu" },
      'shangri-la shenzhen': { dist: 3, zone: "Luohu" },
      'intercontinental shenzhen': { dist: 4, zone: "Nanshan" },
      'hilton shenzhen': { dist: 3, zone: "Futian" },
      'marriott shenzhen': { dist: 3, zone: "Futian" },
      'westin shenzhen': { dist: 3, zone: "Futian" },
      'w shenzhen': { dist: 3, zone: "Futian" },
      'conrad shenzhen': { dist: 3, zone: "Futian" },
      'andaz shenzhen': { dist: 4, zone: "Nanshan" },
      'edition shenzhen': { dist: 4, zone: "Nanshan" },
      'futian': { dist: 5, zone: "Futian" },
      'luohu': { dist: 3, zone: "Luohu" },
      'nanshan': { dist: 8, zone: "Nanshan" },
      'yantian': { dist: 15, zone: "Yantian" },
      'longgang': { dist: 20, zone: "Longgang" },
      'baoan': { dist: 12, zone: "Baoan" },
      'longhua': { dist: 15, zone: "Longhua" },
      'pingshan': { dist: 35, zone: "Pingshan" },
      'guangming': { dist: 25, zone: "Guangming" },
      'dapeng': { dist: 40, zone: "Dapeng" },
      'shekou': { dist: 10, zone: "Nanshan" },
      'window of the world': { dist: 8, zone: "Nanshan" },
      'happy valley': { dist: 8, zone: "Nanshan" },
      'shenzhen bay': { dist: 8, zone: "Nanshan" },
      'civic center': { dist: 3, zone: "Futian" },
      'coco park': { dist: 3, zone: "Futian" },
      'dongmen': { dist: 3, zone: "Luohu" },
      'huaqiangbei': { dist: 4, zone: "Futian" },
      'baoan airport': { dist: 0, zone: "SZX" },
      'shenzhen airport': { dist: 0, zone: "SZX" },
      'shenzhen north': { dist: 10, zone: "Longhua" },
      'shenzhen railway': { dist: 3, zone: "Luohu" },
      'shenzhen bay port': { dist: 10, zone: "Nanshan" },
      'huanggang port': { dist: 5, zone: "Futian" },
      'luohu port': { dist: 3, zone: "Luohu" },
      'default': { dist: 20, zone: "City Center" }
    }
  },
  chengdu: {
    airports: { TFU: 50, CTU: 20 },
    zones: {
      'ritz carlton chengdu': { dist: 3, zone: "Jinjiang" },
      'four seasons chengdu': { dist: 4, zone: "Jinjiang" },
      'st regis chengdu': { dist: 3, zone: "Jinjiang" },
      'park hyatt chengdu': { dist: 3, zone: "Jinjiang" },
      'mandarin oriental chengdu': { dist: 3, zone: "Jinjiang" },
      'intercontinental chengdu': { dist: 4, zone: "Jinjiang" },
      'shangri-la chengdu': { dist: 3, zone: "Jinjiang" },
      'grand hyatt chengdu': { dist: 3, zone: "Jinjiang" },
      'hilton chengdu': { dist: 4, zone: "Chenghua" },
      'marriott chengdu': { dist: 4, zone: "Chenghua" },
      'sheraton chengdu': { dist: 4, zone: "Chenghua" },
      'westin chengdu': { dist: 3, zone: "Jinjiang" },
      'w chengdu': { dist: 3, zone: "Jinjiang" },
      'niccolo chengdu': { dist: 3, zone: "Jinjiang" },
      'temple house': { dist: 3, zone: "Qingyang" },
      'jinli': { dist: 3, zone: "Wuhou" },
      'kuanzhai': { dist: 3, zone: "Qingyang" },
      'tianfu square': { dist: 2, zone: "Jinjiang" },
      'chunxi road': { dist: 3, zone: "Jinjiang" },
      'jintang': { dist: 3, zone: "Jinjiang" },
      'jinjiang': { dist: 3, zone: "Jinjiang" },
      'qingyang': { dist: 4, zone: "Qingyang" },
      'wuhou': { dist: 4, zone: "Wuhou" },
      'chenghua': { dist: 5, zone: "Chenghua" },
      'longquanyi': { dist: 15, zone: "Longquanyi" },
      'wenjiang': { dist: 15, zone: "Wenjiang" },
      'shuangliu': { dist: 15, zone: "Shuangliu" },
      'pixian': { dist: 15, zone: "Pidu" },
      'pidu': { dist: 15, zone: "Pidu" },
      'xinjin': { dist: 25, zone: "Xinjin" },
      'dujiangyan': { dist: 40, zone: "Dujiangyan" },
      'qingchengshan': { dist: 45, zone: "Qingchengshan" },
      'panda base': { dist: 12, zone: "Chenghua" },
      'chengdu research': { dist: 12, zone: "Chenghua" },
      'tianfu airport': { dist: 0, zone: "TFU" },
      'chengdu tianfu': { dist: 0, zone: "TFU" },
      'shuangliu airport': { dist: 0, zone: "CTU" },
      'chengdu shuangliu': { dist: 0, zone: "CTU" },
      'chengdu east': { dist: 8, zone: "Chenghua" },
      'chengdu railway': { dist: 3, zone: "Jinjiang" },
      'default': { dist: 15, zone: "City Center" }
    }
  },
  hangzhou: {
    airports: { HGH: 30 },
    zones: {
      'four seasons hangzhou': { dist: 5, zone: "West Lake" },
      'park hyatt hangzhou': { dist: 3, zone: "West Lake" },
      'ritz carlton hangzhou': { dist: 3, zone: "West Lake" },
      'intercontinental hangzhou': { dist: 3, zone: "West Lake" },
      'grand hyatt hangzhou': { dist: 3, zone: "West Lake" },
      'sheraton hangzhou': { dist: 5, zone: "West Lake" },
      'hilton hangzhou': { dist: 4, zone: "West Lake" },
      'marriott hangzhou': { dist: 4, zone: "West Lake" },
      'shangri-la hangzhou': { dist: 3, zone: "West Lake" },
      'westin hangzhou': { dist: 3, zone: "West Lake" },
      'amanfayun': { dist: 8, zone: "West Lake" },
      'amanfayun hangzhou': { dist: 8, zone: "West Lake" },
      'amandayan': { dist: 8, zone: "West Lake" },
      'west lake': { dist: 3, zone: "West Lake" },
      'xihu': { dist: 3, zone: "West Lake" },
      'longjing': { dist: 8, zone: "Longjing" },
      'lingyin': { dist: 8, zone: "Lingyin" },
      'shangcheng': { dist: 2, zone: "Shangcheng" },
      'xihu district': { dist: 3, zone: "Xihu" },
      'jianggan': { dist: 5, zone: "Jianggan" },
      'gongshu': { dist: 4, zone: "Gongshu" },
      'binjiang': { dist: 6, zone: "Binjiang" },
      'xiaoshan': { dist: 15, zone: "Xiaoshan" },
      'yuhang': { dist: 15, zone: "Yuhang" },
      'tonglu': { dist: 50, zone: "Tonglu" },
      'chunan': { dist: 60, zone: "Chunan" },
      'jiande': { dist: 70, zone: "Jiande" },
      'linan': { dist: 30, zone: "Linan" },
      'fuyang': { dist: 20, zone: "Fuyang" },
      'linping': { dist: 15, zone: "Linping" },
      'qiandao lake': { dist: 100, zone: "Qiandao Lake" },
      'xixi wetland': { dist: 8, zone: "Xixi" },
      'grand canal': { dist: 4, zone: "Gongshu" },
      'hangzhou east': { dist: 5, zone: "Jianggan" },
      'hangzhou railway': { dist: 3, zone: "Shangcheng" },
      'xiaoshan airport': { dist: 0, zone: "HGH" },
      'hangzhou airport': { dist: 0, zone: "HGH" },
      'default': { dist: 10, zone: "City Center" }
    }
  },
  wuhan: {
    airports: { WUH: 30 },
    zones: {
      'ritz carlton wuhan': { dist: 3, zone: "Jianghan" },
      'park hyatt wuhan': { dist: 3, zone: "Jianghan" },
      'grand hyatt wuhan': { dist: 3, zone: "Jianghan" },
      'shangri-la wuhan': { dist: 4, zone: "Wuchang" },
      'hilton wuhan': { dist: 4, zone: "Wuchang" },
      'marriott wuhan': { dist: 4, zone: "Wuchang" },
      'intercontinental wuhan': { dist: 5, zone: "Wuchang" },
      'sheraton wuhan': { dist: 4, zone: "Wuchang" },
      'westin wuhan': { dist: 3, zone: "Jianghan" },
      'conrad wuhan': { dist: 4, zone: "Wuchang" },
      'marco polo': { dist: 3, zone: "Jianghan" },
      'jianghan': { dist: 3, zone: "Jianghan" },
      'wuchang': { dist: 5, zone: "Wuchang" },
      'hanyang': { dist: 5, zone: "Hanyang" },
      'qiaokou': { dist: 4, zone: "Qiaokou" },
      'dongxihu': { dist: 10, zone: "Dongxihu" },
      'jiangxia': { dist: 15, zone: "Jiangxia" },
      'huangpi': { dist: 25, zone: "Huangpi" },
      'xinzhou': { dist: 30, zone: "Xinzhou" },
      'caidian': { dist: 20, zone: "Caidian" },
      'hongshan': { dist: 8, zone: "Hongshan" },
      'qingshan': { dist: 10, zone: "Qingshan" },
      'yellow crane tower': { dist: 5, zone: "Wuchang" },
      'east lake': { dist: 8, zone: "Wuchang" },
      'han street': { dist: 5, zone: "Wuchang" },
      'guqin tai': { dist: 6, zone: "Hanyang" },
      'wuhan tianhe': { dist: 0, zone: "WUH" },
      'wuhan airport': { dist: 0, zone: "WUH" },
      'wuhan railway': { dist: 3, zone: "Jianghan" },
      'wuhan east': { dist: 8, zone: "Hongshan" },
      'default': { dist: 15, zone: "City Center" }
    }
  },
  xian: {
    airports: { XIY: 40 },
    zones: {
      'ritz carlton xian': { dist: 3, zone: "Yanta" },
      'park hyatt xian': { dist: 3, zone: "Yanta" },
      'grand hyatt xian': { dist: 3, zone: "Yanta" },
      'sofitel xian': { dist: 2, zone: "Beilin" },
      'hilton xian': { dist: 4, zone: "Yanta" },
      'marriott xian': { dist: 4, zone: "Yanta" },
      'shangri-la xian': { dist: 4, zone: "Yanta" },
      'intercontinental xian': { dist: 2, zone: "Beilin" },
      'westin xian': { dist: 2, zone: "Beilin" },
      'w xian': { dist: 4, zone: "Qujiang" },
      'bell tower': { dist: 2, zone: "Beilin" },
      'drum tower': { dist: 2, zone: "Beilin" },
      'city wall': { dist: 2, zone: "Beilin" },
      'muslim quarter': { dist: 2, zone: "Lianhu" },
      'huimin street': { dist: 2, zone: "Lianhu" },
      'big wild goose': { dist: 5, zone: "Yanta" },
      'dayan pagoda': { dist: 5, zone: "Yanta" },
      'terracotta': { dist: 30, zone: "Lintong" },
      'bampo museum': { dist: 3, zone: "Beilin" },
      'yanta': { dist: 5, zone: "Yanta" },
      'beilin': { dist: 2, zone: "Beilin" },
      'lianhu': { dist: 3, zone: "Lianhu" },
      'weiyang': { dist: 8, zone: "Weiyang" },
      'baqiao': { dist: 10, zone: "Baqiao" },
      'changan': { dist: 12, zone: "Changan" },
      'yanliang': { dist: 30, zone: "Yanliang" },
      'lintong': { dist: 25, zone: "Lintong" },
      'xianyang': { dist: 20, zone: "Xianyang" },
      'xian airport': { dist: 0, zone: "XIY" },
      'xianyang airport': { dist: 0, zone: "XIY" },
      'xian railway': { dist: 3, zone: "Beilin" },
      'xian north': { dist: 10, zone: "Weiyang" },
      'default': { dist: 15, zone: "City Center" }
    }
  },
  chongqing: {
    airports: { CKG: 25 },
    zones: {
      'ritz carlton chongqing': { dist: 3, zone: "Jiefangbei" },
      'intercontinental chongqing': { dist: 3, zone: "Jiefangbei" },
      'grand hyatt chongqing': { dist: 3, zone: "Jiefangbei" },
      'westin chongqing': { dist: 3, zone: "Jiefangbei" },
      'sheraton chongqing': { dist: 4, zone: "Yuzhong" },
      'marriott chongqing': { dist: 4, zone: "Yuzhong" },
      'hilton chongqing': { dist: 4, zone: "Yuzhong" },
      'niccolo chongqing': { dist: 3, zone: "Jiangbei" },
      'jiefangbei': { dist: 2, zone: "Jiefangbei" },
      'yuzhong': { dist: 3, zone: "Yuzhong" },
      'jiangbei': { dist: 5, zone: "Jiangbei" },
      'nanan': { dist: 6, zone: "Nanan" },
      'shapingba': { dist: 8, zone: "Shapingba" },
      'jiulongpo': { dist: 8, zone: "Jiulongpo" },
      'dadukou': { dist: 10, zone: "Dadukou" },
      'beibei': { dist: 20, zone: "Beibei" },
      'banan': { dist: 15, zone: "Banan" },
      'wanzhou': { dist: 200, zone: "Wanzhou" },
      'fuling': { dist: 80, zone: "Fuling" },
      'cable car': { dist: 3, zone: "Yuzhong" },
      'hongya cave': { dist: 3, zone: "Yuzhong" },
      'three gorges': { dist: 5, zone: "Yuzhong" },
      'chongqing airport': { dist: 0, zone: "CKG" },
      'jiangbei airport': { dist: 0, zone: "CKG" },
      'chongqing north': { dist: 5, zone: "Jiangbei" },
      'chongqing railway': { dist: 3, zone: "Yuzhong" },
      'default': { dist: 15, zone: "City Center" }
    }
  },
  nanjing: {
    airports: { NKG: 35 },
    zones: {
      'ritz carlton nanjing': { dist: 3, zone: "Xinjiekou" },
      'intercontinental nanjing': { dist: 3, zone: "Xinjiekou" },
      'grand hyatt nanjing': { dist: 3, zone: "Xinjiekou" },
      'shangri-la nanjing': { dist: 4, zone: "Gulou" },
      'hilton nanjing': { dist: 4, zone: "Gulou" },
      'marriott nanjing': { dist: 4, zone: "Gulou" },
      'xinjiekou': { dist: 2, zone: "Xinjiekou" },
      'gulou': { dist: 4, zone: "Gulou" },
      'qinhuai': { dist: 3, zone: "Qinhuai" },
      'jianye': { dist: 5, zone: "Jianye" },
      'xuanwu': { dist: 5, zone: "Xuanwu" },
      'qinhuai river': { dist: 3, zone: "Qinhuai" },
      'confucius temple': { dist: 3, zone: "Qinhuai" },
      'nanjing airport': { dist: 0, zone: "NKG" },
      'lukou airport': { dist: 0, zone: "NKG" },
      'nanjing south': { dist: 8, zone: "Yuhuatai" },
      'nanjing railway': { dist: 3, zone: "Xuanwu" },
      'default': { dist: 15, zone: "City Center" }
    }
  },
  suzhou: {
    airports: { SHA: 80 },
    zones: {
      'park hyatt suzhou': { dist: 3, zone: "Gusu" },
      'intercontinental suzhou': { dist: 3, zone: "Gusu" },
      'shangri-la suzhou': { dist: 4, zone: "Gusu" },
      'marriott suzhou': { dist: 4, zone: "Gusu" },
      'gusu': { dist: 3, zone: "Gusu" },
      'pingjiang': { dist: 3, zone: "Gusu" },
      'suzhou industrial': { dist: 10, zone: "SIP" },
      'sip': { dist: 10, zone: "SIP" },
      'tiger hill': { dist: 5, zone: "Gusu" },
      'humble administrator': { dist: 4, zone: "Gusu" },
      'lingering garden': { dist: 4, zone: "Gusu" },
      'suzhou railway': { dist: 3, zone: "Gusu" },
      'suzhou north': { dist: 8, zone: "Xiangcheng" },
      'default': { dist: 15, zone: "City Center" }
    }
  },
  tianjin: {
    airports: { TSN: 15 },
    zones: {
      'ritz carlton tianjin': { dist: 3, zone: "Heping" },
      'shangri-la tianjin': { dist: 4, zone: "Heping" },
      'hilton tianjin': { dist: 4, zone: "Heping" },
      'marriott tianjin': { dist: 4, zone: "Heping" },
      'heping': { dist: 3, zone: "Heping" },
      'hexi': { dist: 5, zone: "Hexi" },
      'nankai': { dist: 4, zone: "Nankai" },
      'hebei district': { dist: 4, zone: "Hebei" },
      'hongqiao tj': { dist: 5, zone: "Hongqiao" },
      'binhai': { dist: 30, zone: "Binhai" },
      'teda': { dist: 35, zone: "TEDA" },
      'tianjin airport': { dist: 0, zone: "TSN" },
      'binhai airport': { dist: 0, zone: "TSN" },
      'tianjin railway': { dist: 3, zone: "Hebei" },
      'tianjin west': { dist: 5, zone: "Hongqiao" },
      'tianjin south': { dist: 8, zone: "Xiqing" },
      'default': { dist: 15, zone: "City Center" }
    }
  },
  qingdao: {
    airports: { TAO: 30 },
    zones: {
      'shangri-la qingdao': { dist: 4, zone: "Shinan" },
      'intercontinental qingdao': { dist: 4, zone: "Shinan" },
      'hilton qingdao': { dist: 4, zone: "Shinan" },
      'hyatt qingdao': { dist: 5, zone: "Laoshan" },
      'shinan': { dist: 3, zone: "Shinan" },
      'laoshan': { dist: 15, zone: "Laoshan" },
      'licang': { dist: 8, zone: "Licang" },
      'chengyang': { dist: 15, zone: "Chengyang" },
      'huangdao': { dist: 20, zone: "Huangdao" },
      'badaguan': { dist: 5, zone: "Shinan" },
      'zhanqiao': { dist: 3, zone: "Shinan" },
      'qingdao beer': { dist: 5, zone: "Shibei" },
      'qingdao airport': { dist: 0, zone: "TAO" },
      'qingdao railway': { dist: 3, zone: "Shinan" },
      'qingdao north': { dist: 8, zone: "Shibei" },
      'default': { dist: 15, zone: "City Center" }
    }
  },
  xiamen: {
    airports: { XMN: 15 },
    zones: {
      'shangri-la xiamen': { dist: 3, zone: "Siming" },
      'hilton xiamen': { dist: 3, zone: "Siming" },
      'marriott xiamen': { dist: 3, zone: "Siming" },
      'intercontinental xiamen': { dist: 4, zone: "Siming" },
      'siming': { dist: 3, zone: "Siming" },
      'huli': { dist: 5, zone: "Huli" },
      'jimei': { dist: 15, zone: "Jimei" },
      'haicang': { dist: 15, zone: "Haicang" },
      'tongan': { dist: 25, zone: "Tongan" },
      "xiang'an": { dist: 20, zone: "Xiang'an" },
      'gulangyu': { dist: 4, zone: "Gulangyu" },
      'zhongshan road': { dist: 3, zone: "Siming" },
      'xiamen airport': { dist: 0, zone: "XMN" },
      'gaoqi airport': { dist: 0, zone: "XMN" },
      'xiamen railway': { dist: 3, zone: "Siming" },
      'xiamen north': { dist: 15, zone: "Jimei" },
      'default': { dist: 10, zone: "City Center" }
    }
  },
  dalian: {
    airports: { DLC: 15 },
    zones: {
      'shangri-la dalian': { dist: 3, zone: "Zhongshan" },
      'hilton dalian': { dist: 3, zone: "Zhongshan" },
      'intercontinental dalian': { dist: 3, zone: "Zhongshan" },
      'zhongshan': { dist: 3, zone: "Zhongshan" },
      'xigang': { dist: 4, zone: "Xigang" },
      'shahekou': { dist: 5, zone: "Shahekou" },
      'ganjingzi': { dist: 8, zone: "Ganjingzi" },
      'jinzhou': { dist: 20, zone: "Jinzhou" },
      'development zone': { dist: 25, zone: "Development Zone" },
      'lvshunkou': { dist: 35, zone: "Lvshunkou" },
      'xinghai square': { dist: 5, zone: "Shahekou" },
      'dalian airport': { dist: 0, zone: "DLC" },
      'dalian railway': { dist: 3, zone: "Zhongshan" },
      'dalian north': { dist: 10, zone: "Ganjingzi" },
      'default': { dist: 10, zone: "City Center" }
    }
  },
  changsha: {
    airports: { CSX: 25 },
    zones: {
      'ritz carlton changsha': { dist: 3, zone: "Furong" },
      'intercontinental changsha': { dist: 3, zone: "Furong" },
      'grand hyatt changsha': { dist: 3, zone: "Furong" },
      'westin changsha': { dist: 3, zone: "Furong" },
      'shangri-la changsha': { dist: 4, zone: "Tianxin" },
      'hilton changsha': { dist: 4, zone: "Furong" },
      'furong': { dist: 3, zone: "Furong" },
      'tianxin': { dist: 4, zone: "Tianxin" },
      'yuelu': { dist: 5, zone: "Yuelu" },
      'kaifu': { dist: 4, zone: "Kaifu" },
      'wangcheng': { dist: 10, zone: "Wangcheng" },
      'yuhua': { dist: 5, zone: "Yuhua" },
      'changsha county': { dist: 10, zone: "Changsha County" },
      'orangery': { dist: 3, zone: "Furong" },
      'juzizhou': { dist: 3, zone: "Furong" },
      'yuelu mountain': { dist: 5, zone: "Yuelu" },
      'changsha airport': { dist: 0, zone: "CSX" },
      'huanghua airport': { dist: 0, zone: "CSX" },
      'changsha south': { dist: 8, zone: "Yuhua" },
      'changsha railway': { dist: 3, zone: "Furong" },
      'default': { dist: 15, zone: "City Center" }
    }
  },
  zhengzhou: {
    airports: { CGO: 35 },
    zones: {
      'jw marriott zhengzhou': { dist: 3, zone: "Jinshui" },
      'hilton zhengzhou': { dist: 3, zone: "Jinshui" },
      'shangri-la zhengzhou': { dist: 3, zone: "Jinshui" },
      'intercontinental zhengzhou': { dist: 3, zone: "Jinshui" },
      'jinshui': { dist: 3, zone: "Jinshui" },
      'zhongyuan': { dist: 4, zone: "Zhongyuan" },
      'erqi': { dist: 3, zone: "Erqi" },
      'guancheng': { dist: 4, zone: "Guancheng" },
      'huiji': { dist: 8, zone: "Huiji" },
      'shangjie': { dist: 15, zone: "Shangjie" },
      'dengfeng': { dist: 50, zone: "Dengfeng" },
      'shaolin': { dist: 60, zone: "Shaolin" },
      'zhengzhou airport': { dist: 0, zone: "CGO" },
      'xinzheng airport': { dist: 0, zone: "CGO" },
      'zhengzhou east': { dist: 8, zone: "Jinshui" },
      'zhengzhou railway': { dist: 3, zone: "Erqi" },
      'default': { dist: 15, zone: "City Center" }
    }
  },
  harbin: {
    airports: { HRB: 35 },
    zones: {
      'shangri-la harbin': { dist: 3, zone: "Daoli" },
      'hilton harbin': { dist: 3, zone: "Daoli" },
      'marriott harbin': { dist: 3, zone: "Nangang" },
      'daoli': { dist: 3, zone: "Daoli" },
      'nangang': { dist: 4, zone: "Nangang" },
      'daowai': { dist: 4, zone: "Daowai" },
      'xiangfang': { dist: 6, zone: "Xiangfang" },
      'pingfang': { dist: 15, zone: "Pingfang" },
      'songbei': { dist: 8, zone: "Songbei" },
      'hulan': { dist: 20, zone: "Hulan" },
      'acheng': { dist: 25, zone: "Acheng" },
      'shuangcheng': { dist: 30, zone: "Shuangcheng" },
      'central street': { dist: 3, zone: "Daoli" },
      'sophia church': { dist: 3, zone: "Daoli" },
      'sun island': { dist: 5, zone: "Songbei" },
      'ice festival': { dist: 5, zone: "Songbei" },
      'harbin airport': { dist: 0, zone: "HRB" },
      'taiping airport': { dist: 0, zone: "HRB" },
      'harbin railway': { dist: 3, zone: "Nangang" },
      'harbin west': { dist: 5, zone: "Nangang" },
      'default': { dist: 15, zone: "City Center" }
    }
  },
  jinan: {
    airports: { TNA: 30 },
    zones: {
      'shangri-la jinan': { dist: 3, zone: "Lixia" },
      'hilton jinan': { dist: 3, zone: "Lixia" },
      'marriott jinan': { dist: 3, zone: "Shizhong" },
      'intercontinental jinan': { dist: 3, zone: "Lixia" },
      'lixia': { dist: 3, zone: "Lixia" },
      'shizhong': { dist: 4, zone: "Shizhong" },
      'tianqiao': { dist: 4, zone: "Tianqiao" },
      'huaiyin': { dist: 5, zone: "Huaiyin" },
      'licheng': { dist: 10, zone: "Licheng" },
      'changqing': { dist: 15, zone: "Changqing" },
      'zhangqiu': { dist: 20, zone: "Zhangqiu" },
      'baoshan': { dist: 15, zone: "Baoshan" },
      'daming lake': { dist: 3, zone: "Lixia" },
      'baotu spring': { dist: 3, zone: "Lixia" },
      'thousand buddha': { dist: 4, zone: "Lixia" },
      'jinan airport': { dist: 0, zone: "TNA" },
      'yaoqiang airport': { dist: 0, zone: "TNA" },
      'jinan railway': { dist: 3, zone: "Tianqiao" },
      'jinan west': { dist: 8, zone: "Huaiyin" },
      'default': { dist: 15, zone: "City Center" }
    }
  },
};

// ============================================================
//  SMART DISTANCE ESTIMATION FUNCTIONS
// ============================================================

function smartDistanceEstimate(address, city, airport) {
  if (!address || !city) return null;
  var cityData = cityZones[city];
  if (!cityData) return null;
  var lowerAddr = address.toLowerCase().trim();
  var zones = cityData.zones;
  var bestMatch = null;
  var bestMatchLength = 0;
  for (var keyword in zones) {
    if (keyword === 'default') continue;
    var lowerKeyword = keyword.toLowerCase();
    if (lowerAddr.indexOf(lowerKeyword) !== -1) {
      if (lowerKeyword.length > bestMatchLength) {
        bestMatch = zones[keyword];
        bestMatchLength = lowerKeyword.length;
      }
    }
  }
  var matchedData = bestMatch || zones['default'] || { dist: 20, zone: 'City Center' };
  var airportDist = cityData.airports[airport];
  if (!airportDist) {
    var apKeys = Object.keys(cityData.airports);
    airportDist = apKeys.length > 0 ? cityData.airports[apKeys[0]] : 30;
  }
  var totalDist = airportDist + matchedData.dist;
  var range = '0-30';
  if (totalDist > 80) range = '80+';
  else if (totalDist > 50) range = '50-80';
  else if (totalDist > 30) range = '30-50';
  return { dist: matchedData.dist, zone: matchedData.zone, range: range, totalDist: totalDist, airportDist: airportDist };
}

function getDistanceRangeLabel(range) {
  var map = { '0-30': '0-30 km', '30-50': '30-50 km', '50-80': '50-80 km', '80+': '80+ km' };
  return map[range] || range;
}

function getDistanceMultiplier(range) {
  var map = { '0-30': 1.0, '30-50': 1.3, '50-80': 1.6, '80+': 2.0 };
  return map[range] || 1.0;
}

function getAirportsForCity(city) {
  var cityData = cityZones[city];
  if (!cityData) return [{ code: 'INTL', name: 'International Airport', dist: 30 }];
  var result = [];
  for (var code in cityData.airports) {
    result.push({ code: code, name: getAirportName(city, code), dist: cityData.airports[code] });
  }
  return result;
}

function getAirportName(city, code) {
  var names = {
    PVG: 'Shanghai Pudong (PVG)', SHA: 'Shanghai Hongqiao (SHA)',
    PEK: 'Beijing Capital (PEK)', PKX: 'Beijing Daxing (PKX)',
    CAN: 'Guangzhou Baiyun (CAN)', SZX: 'Shenzhen Baoan (SZX)',
    TFU: 'Chengdu Tianfu (TFU)', CTU: 'Chengdu Shuangliu (CTU)',
    HGH: 'Hangzhou Xiaoshan (HGH)', WUH: 'Wuhan Tianhe (WUH)',
    XIY: "Xi'an Xianyang (XIY)", CKG: 'Chongqing Jiangbei (CKG)',
    NKG: 'Nanjing Lukou (NKG)', TAO: 'Qingdao Liuting (TAO)',
    XMN: 'Xiamen Gaoqi (XMN)', DLC: 'Dalian Zhoushuizi (DLC)',
    CSX: 'Changsha Huanghua (CSX)', CGO: 'Zhengzhou Xinzheng (CGO)',
    HRB: 'Harbin Taiping (HRB)', TNA: 'Jinan Yaoqiang (TNA)',
    TSN: 'Tianjin Binhai (TSN)'
  };
  return names[code] || code + ' Airport';
}